{
 "title": "Email Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Email Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "inbound_mails_by_email",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(email) (increase(log_metric_gauge_all_inbound_mails[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outbound_mails_by_email",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(email) (increase(log_metric_gauge_all_outbound_mails[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate_inbound_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(log_metric_counter_count_all_inbound_mails[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate_outbound_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(log_metric_counter_count_all_outbound_mails[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inbound_email_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "log_metric_counter_count_all_inbound_mails",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outbound_email_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "log_metric_counter_count_all_outbound_mails",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}