{
 "title": "Eviz Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "from", "query": "from= " },
   { "name": "fromvalue" },
   { "name": "to", "query": "to=" },
   { "name": "tovalue" },
   { "name": "identifier" }
  ]
 },
 "panels": [
  {
   "title": "InBound OutBound Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/mail.log\", job=\"mail_logs\"} |= `$from` |= `$fromvalue` |= `$to` |= `$tovalue`"
    }
   ]
  },
  {
   "title": "Raw logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/mail.log\", job=\"mail_logs\"} |= `$identifier`"
    }
   ]
  },
  {
   "title": "Raw logs Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/mail.log\", job=\"mail_logs\"} |= `$identifier` [$__auto])"
    }
   ]
  }
 ]
}